apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-server
  selector:
    app: guestbook
  type: {{ .Values.service.type }}
