apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 80